package templates.common.networking;

import java.io.Serializable;

public enum PacketType implements Serializable {
    // Server to client
    USERNAME_PROMPT,
    USERNAME_SUCCESS,
    LEVEL_IS_READY,
    PHYSICAL_OBJECT_ADDED_TO_LEVEL,
    PHYSICAL_OBJECT_REMOVED_FROM_LEVEL,
    PHYSICAL_OBJECT_MOVED,
    PHYSICAL_OBJECT_ROTATED,
    PHYSICAL_OBJECT_SCALED,
    PHYSICAL_OBJECT_TRANSFORM_CHANGED,
    AABB_HITBOX_ADDED,
    AABB_HITBOX_REMOVED,
    SPHERE_HITBOX_ADDED,
    SPHERE_HITBOX_REMOVED,
    CONNECTED_PLAYER_ADDED,
    CONNECTED_PLAYER_TRANSFORM_CHANGED,
    CONNECTED_PLAYER_LEFT,
    LEVEL_SECONDS_PER_GAME_TICK_CHANGED,
    LEVEL_GRAVITY_CHANGED,
    CONFIRM_CHAT_MESSAGE_RECEPTION,
    BROADCASTING_CHAT_MESSAGE,
    BROADCASTING_SYSTEM_MESSAGE,
    VIRTUAL_LIGHT_ADDED,
    VIRTUAL_LIGHT_REMOVED,
    VIRTUAL_LIGHT_MOVED,
    VIRTUAL_LIGHT_COLOR_CHANGED,
    VIRTUAL_LIGHT_ATTENUATION_CHANGED,
    VIRTUAL_LIGHT_PROPERTIES_CHANGED,
    VIRTUAL_DIRECTIONAL_LIGHT_ADDED,
    VIRTUAL_DIRECTIONAL_LIGHT_REMOVED,
    VIRTUAL_DIRECTIONAL_LIGHT_DIRECTION_CHANGED,
    VIRTUAL_DIRECTIONAL_LIGHT_COLOR_CHANGED,
    VIRTUAL_DIRECTIONAL_LIGHT_PROPERTIES_CHANGED,
    SKYBOX_CHANGED,
    PLAY_SOUND_AT_PHYSICAL_OBJECT,
    PLAY_SOUND_AT_POSITION,
    CREATE_SOUND_EMITTER,
    DESTROY_SOUND_EMITTER,
    PLAY_SOUND_AT_SOUND_EMITTER,
    UPDATE_POSITION_OF_SOUND_EMITTER,

    // Client to server
    PLAYER_USERNAME,
    PLAYER_JOINED,
    PLAYER_MOVED,
    LEVEL_CHANGE_PAUSE_STATE,
    CHAT_MESSAGE
}
